name: "emsdk"
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      pages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Setup
        uses: mymindstorm/setup-emsdk@v14
        with:
          actions-cache-folder: 'emsdk-cache'
      
      - name: Build
        run: |
          mkdir -p build
          cd build
          emcmake cmake .. -DPLATFORM=Web
          emmake make
          mkdir -p prepare
          mv void_wars.* prepare/.
          mv prepare/void_wars.html prepare/index.html
      - name: Upload GitHub Pages artifact
        uses: actions/upload-pages-artifact@v3.0.1
        with:
          path: build/prepare
      - name: Deploy
        uses: actions/deploy-pages@v4.0.5
    
